

settings:
    noconfirm: false
    apps_module:
        install_cmd_types:
            apt: sudo apt --assume-yes install $@
            flatpak: flatpak install -y --noninteractive $@
            pacman: sudo pacman -S --noconfirm --needed $@
            yay: yay -S --noconfirm --needed $@
    files_module:
        install_cmd_types:
            copy:
            hardlink:
            tar_copy: tar -xPf "$1.tar"
            compress: tar -xPf "$1.tar.xz"
            encrypt: openssl enc -d -aes-256-cbc -md sha512 -pbkdf2 -salt -in "$1.tar.xz.enc" | tar -xPf -
        backup_cmd_types:
            copy:
            hardlink:
            tar_copy: tar -cPf "$1.tar" "${@:2}"
            compress: tar -cJPf "$1.tar.xz" "${@:2}"
            encrypt: tar -cJPf - "${@:2}" | openssl enc -e -aes-256-cbc -md sha512 -pbkdf2 -salt -out "$1.tar.xz.enc"
    system_cmds:
        superuser: sudo
        cp: cp -at "$1" "${@:2}"
        mv: mv -t "$1" "${@:2}"
        mkdir: mkdir -p $1
        validate_path: [ -e "$1" ]
        validate_dir: [ -d "$1" ]

packs:
    pack1:
        pin: 1
        desc: some pack that has stuff
        modules:
            - MODULE: packs
              packs: pack2 pack3
              ALT:
                ubuntu:
                    depends: ...
            - MODULE: apps
              apps: app1 app2 ...
              install_type: flatpak
            - MODULE: files
              files: path/to/file other/path
