
######################

# NOTES:
# CONVERTING STR, LIST[STR] for values that should be list[str], allowing both str or list[str]
#     1. single-line delims by space; 2. multi-line delims by \n; 3. list is list
#     mention somewhere limits of 1. and 3. with quotes and special characters
# "VALIDATE" OPTION (and maybe options for this option, e.g. "validate packs"?)?
#     would parse config and print any possibly useful information
# SCRIPT SHOULD FIND DISTROS BY looking through what is currently called defaults, regardless of if
#     one exists obscurely in a pack - however, give user an option to enter a custom one by -> #custom_default
# YAML SYNTAX RESOURCES:
#    https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
# USE OF EXTENDS scrapped, however instead users can use built-in yaml anchors which would be just as good, if not better

predefined:
    alias_prefix: //
    app_install_types:
        APT: sudo apt --assume-yes install $@
        FLATPAK: flatpak install -y --noninteractive $@
        PACMAN: sudo pacman -S --noconfirm --needed $@
        PARU: paru -S --noconfirm --needed $@
    file_backup_types:
        COPY:
            EXTRACT:
            CREATE:
        HARDLINK:
            EXTRACT:
            CREATE:
        TAR_COPY:
            EXTRACT: tar -xPf "$1.tar"
            CREATE: tar -cPf "$1.tar" "${@:2}"
        COMPRESS:
            EXTRACT: tar -xPf "$1.tar.xz"
            CREATE: tar -cJPf "$1.tar.xz" "${@:2}"
        ENCRYPT:
            EXTRACT: openssl enc -d -aes-256-cbc -md sha512 -pbkdf2 -salt -in "$1.tar.xz.enc" | tar -xPf -
            CREATE: tar -cJPf - "${@:2}" | openssl enc -e -aes-256-cbc -md sha512 -pbkdf2 -salt -out "$1.tar.xz.enc"
    fallback_settings:
        depends: []
        apps: []
        files: []
        app_settings:
            install_type: null
        file_settings:
            backup_type: COPY
            backup_paths: ./backups
            backup_keep: 1
            dump_dir: /tmp/linux-autosetup-dump
            tmp_dir: /tmp/linux-autosetup
        install_cmd: null
        backup_cmd: null
        error_handling: PROMPT

# OVERRIDE IN THIS ORDER?:
# defaults[all] -> defaults[distro] -> pack[all] -> pack[distro]
packs:
    defaults:
        ubuntu:
            apps: []
            files: []
            app_settings:
                install_type: null
            file_settings:
                backup_type: COPY
                backup_paths: ./backups
                backup_keep: 1
                dump_dir: /tmp/linux-autosetup-dump
                tmp_dir: /tmp
            install_cmd: null
            backup_cmd: null
            error_handling: PROMPT
    custom_extra_special_pack_that_shows_off_some_special_stuff:
        all:
            # TODO: when implementing configparser, implement os.path.expandvars() on these paths
            #       and pair with environment variable modifications from Runner class
            files: |
                $HOME/Documents/backups/etc
                path/with spaces/and-quotes/at end "
            # //INSTALL_APPS & //INSTALL_FILES
            # can be used in install_cmd, organized however wanted. automatically place at bottom if not found.
            install_cmd: |
                some_command
                //INSTALL_APPS
                //INSTALL_FILES
            # same as install_cmd, except with //BACKUP_FILES
            backup_cmd: |
                //BACKUP_FILES
        popos:
            depends:

# wip
pack_groups:

